package nz.ac.auckland.bookShare.dto;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementWrapper;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;

import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

@XmlRootElement
@XmlType(name="author")
@XmlAccessorType(XmlAccessType.FIELD)
public class Author extends Person {
	
	@XmlElementWrapper(name = "written-books")
	@XmlElement(name = "bookID")
	private List<Long> _writtenBooks = new ArrayList<Long>();
	
	public Author(){
		this(0, null, null);
	}
	
	/**
	 * Constructs a DTO Parolee instance. This method is intended to be called
	 * by Web service clients when creating new Parolees. The id field is not
	 * required because it is generated by the Web service. Similarly, the
	 * last-known-position field is not required. Of the constructor's
	 * parameters, all fields must be non-null with the exception of curfew,
	 * which is optional (not all Parolees are subject to a curfew).
	 *
	 */
	public Author(String firstName, String lastName) {
		this(0 , firstName, lastName);
	}
	
	/**
	 * Constructs a DTO Parolee instance. This method should NOT be called by 
	 * Web Service clients. It is intended to be used by the Web Service 
	 * implementation when creating a DTO Parolee from a domain-model Parolee 
	 * object.
	 */
	public Author(long id, String firstName, String lastName){
		super(id, firstName, lastName);
	}

	public Collection<Long> getWrittenBooks() {
		return _writtenBooks;
	}

	public void addNewWritten(long bookID) {
		_writtenBooks.add(bookID);
	}
	
	@Override
	public boolean equals(Object obj) {
		if (!(obj instanceof Author))
            return false;
        if (obj == this)
            return true;

        Author rhs = (Author) obj;
        return new EqualsBuilder().
            append(this.getId(), rhs.getId()).
            append(this.getFirstName(), rhs.getFirstName()).
            append(this.getLastName(), rhs.getLastName()).
            append(this.getWrittenBooks(), rhs.getWrittenBooks()).
            isEquals();
	}
	
	@Override
	public int hashCode() {
		return new HashCodeBuilder(17, 31). 
				append(this.getId()).
	            append(this.getFirstName()).
	            append(this.getLastName()).
	            append(this.getWrittenBooks()).
	            toHashCode();
	}
}
